Count handled relation geometries
ad-freiburg/osm2rdf pull request #104
Opened 2024-11-26 17:31 UTC by nicolano

Currently, handled geometries are not counted in the `OsmiumHandler` class. As the geometry is not calculated for every relation, it is first necessary to ensure that the relation is either an area or that it has a geometry.

2025-02-13 16:26 UTC, patrickbr requested changes
Thank you and sorry for the late reply here! There is one issue with your change which we should fix before merging, see my comment.

2025-02-13 16:26 UTC, patrickbr commented on src/osm/OsmiumHandler.cpp
> +        if (osmRelation.isArea() || osmRelation.hasGeometry()) {
Careful: previously, `_progressBar.update(_numTaskDone++);` was protected by `#pragma omp critical(progress)`, but now only the `if` block is protected. Can you put a block around both the if block and `_relationGeometriesHandled++;`?

2025-02-14 09:49 UTC, nicolano commented on src/osm/OsmiumHandler.cpp
> +        if (osmRelation.isArea() || osmRelation.hasGeometry()) {
Thanks for the feedback, i will add the code block

2025-02-14 10:24 UTC, patrickbr approved these changes

2025-02-14 10:25 UTC, patrickbr commented
Thanks, this looks fine now.

2025-02-14 10:30 UTC, merged